services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_recipes
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: recipes
      MYSQL_USER: app
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./init_scripts:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    networks:
      - a4pm

volumes:
  db_data:

networks:
  a4pm:
    driver: bridge